# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0011_alter_history_action'),
        ('detect', '0029_auto_20180903_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='cf',
            field=models.ManyToManyField(blank=True, to='dns.cf_account'),
        ),
    ]
