# Generated by Django 2.0 on 2018-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0032_auto_20180918_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdn_account_t',
            name='name',
            field=models.IntegerField(choices=[(0, 'tencent'), (1, 'wangsu')]),
        ),
    ]
