# Generated by Django 2.0 on 2018-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180812_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manage',
            field=models.IntegerField(choices=[(1, '管理'), (0, '普通')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
