# Generated by Django 2.0 on 2018-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0066_auto_20180918_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns_authority_t',
            name='permission',
            field=models.CharField(choices=[('read', '读权限'), ('change', '改权限'), ('delete', '删权限'), ('add', '增权限'), ('execute', '执行权限')], max_length=10),
        ),
        migrations.AlterField(
            model_name='minion_t',
            name='service_type',
            field=models.CharField(choices=[('nginx', 'nginx'), ('apache', 'apache'), ('mysql', 'mysql'), ('tomcat', 'tomcat'), ('nodejs', 'nodejs'), ('vpn', 'vpn'), ('flask', 'flask'), ('logstash', 'logstash')], default='nginx', max_length=10),
        ),
        migrations.AlterField(
            model_name='permission_t',
            name='permission',
            field=models.CharField(choices=[('read', '读权限'), ('change', '改权限'), ('delete', '删权限'), ('add', '增权限'), ('execute', '执行权限')], max_length=10, unique=True),
        ),
    ]
